import type { PlanStep } from '@agent-forge/shared'

/**
 * Generates a formatted pull request body with implementation details.
 */
export function generatePRBody(
  task: { title: string; description: string; autonomousMode?: boolean },
  planSteps: PlanStep[],
  commitSha: string
): string {
  return `## Summary
${task.description}

## Implementation Steps
${planSteps.map(s => `${s.stepNumber}. ${s.description}`).join('\n')}

## Changes
- Commit: ${commitSha.slice(0, 8)}
- Steps completed: ${planSteps.length}

## Test Plan
- [ ] Unit tests passing
- [ ] Integration tests passing
- [ ] Manual testing completed

---
🤖 Generated by [Loopforge Studio](https://github.com/loopforge-studio)
${task.autonomousMode ? '\n⚠️ **Autonomous Mode**: This PR will be auto-merged after checks pass.' : ''}`
}
