import { PageHeader } from "@/components/institutional/page-header";
import { ProseContent } from "@/components/institutional/prose-content";

export default function TermsPage() {
  return (
    <>
      <PageHeader
        title="Terms of Service"
        subtitle="Last updated: January 2026"
      />

      <ProseContent>
        <h2>Agreement to Terms</h2>
        <p>
          By accessing or using Loopforge Studio (&quot;the Service&quot;), you
          agree to be bound by these Terms of Service (&quot;Terms&quot;). If
          you disagree with any part of these terms, you may not access the
          Service.
        </p>

        <h2>Description of Service</h2>
        <p>
          Loopforge Studio is an AI-powered autonomous development platform that
          allows users to create, manage, and execute coding tasks through a
          visual interface. The Service connects to GitHub repositories and uses
          third-party AI providers to generate and modify code.
        </p>

        <h2>User Accounts</h2>
        <p>To use the Service, you must:</p>
        <ul>
          <li>Have a valid GitHub account</li>
          <li>Provide accurate and complete information</li>
          <li>Maintain the security of your account credentials</li>
          <li>Be at least 13 years of age</li>
        </ul>
        <p>
          You are responsible for all activities that occur under your account.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any applicable laws or regulations</li>
          <li>Infringe on intellectual property rights</li>
          <li>Generate malicious code, malware, or exploits</li>
          <li>Attempt to gain unauthorized access to systems or data</li>
          <li>Interfere with or disrupt the Service</li>
          <li>Use the Service for any illegal or unauthorized purpose</li>
        </ul>

        <h2>API Keys and Third-Party Services</h2>
        <p>
          The Service uses a BYOK (Bring Your Own Key) model. You are
          responsible for:
        </p>
        <ul>
          <li>Obtaining and managing your own API keys from AI providers</li>
          <li>Complying with the terms of service of those providers</li>
          <li>Any charges incurred through your use of third-party APIs</li>
        </ul>

        <h2>Code and Repository Access</h2>
        <p>By connecting a repository to the Service, you:</p>
        <ul>
          <li>
            Grant us temporary access to read and modify files during task
            execution
          </li>
          <li>Confirm you have the right to grant such access</li>
          <li>
            Understand that AI-generated code may require review before merging
          </li>
        </ul>
        <p>
          We do not claim ownership of any code in your repositories. You retain
          all rights to your code.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          Code and content generated by AI through the Service may contain
          errors or require modification. You are responsible for:
        </p>
        <ul>
          <li>Reviewing all AI-generated code before merging</li>
          <li>Testing changes in appropriate environments</li>
          <li>
            Ensuring compliance with your project&apos;s licensing requirements
          </li>
        </ul>

        <h2>Service Availability</h2>
        <p>
          We strive to maintain high availability but do not guarantee
          uninterrupted access. The Service may be temporarily unavailable for
          maintenance, updates, or technical issues.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Loopforge Studio and its
          operators shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages, including but not limited to:
        </p>
        <ul>
          <li>Loss of data or code</li>
          <li>Business interruption</li>
          <li>Errors in AI-generated code</li>
          <li>Security breaches resulting from user negligence</li>
        </ul>

        <h2>Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless Loopforge Studio from any
          claims, damages, or expenses arising from your use of the Service or
          violation of these Terms.
        </p>

        <h2>Open Source License</h2>
        <p>
          Loopforge Studio is open source software. The source code is available
          under the terms specified in the project repository. These Terms of
          Service apply to your use of the hosted Service, not to self-hosted
          deployments.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will
          provide notice of significant changes via email or through the
          Service. Continued use after changes constitutes acceptance.
        </p>

        <h2>Termination</h2>
        <p>
          We may terminate or suspend your account at any time for violation of
          these Terms. You may also delete your account at any time through the
          settings page.
        </p>

        <h2>Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of the jurisdiction in which the Service operates, without regard
          to conflict of law principles.
        </p>

        <h2>Contact</h2>
        <p>
          For questions about these Terms, please contact us at{" "}
          <a href="mailto:legal@loopforge.dev">legal@loopforge.dev</a>.
        </p>
      </ProseContent>
    </>
  );
}
