# These are supported funding model platforms

# GitHub Sponsors (up to 4 usernames)
# github: [username1, username2, username3, username4]

# Patreon
# patreon: username

# Open Collective
# open_collective: projectname

# Ko-fi
# ko_fi: username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Otechie
# otechie: username

# LFX Crowdfunding
# lfx_crowdfunding: project-name

# Custom URLs (up to 4)
# custom: ['https://example.com', 'https://example2.com']
