import { Job } from "bullmq";
import {
  db,
  users,
  tasks,
  executions,
  executionEvents,
  repos,
  repoIndex,
  workerJobs,
  workerEvents,
  taskDependencies,
  activityEvents,
  buildStatusHistoryAppend,
} from "../lib/db";
import type {
  WorkerEventMetadata,
  TaskStatus,
  RepoIndex,
  BillingMode,
  ActivityEventCategory,
} from "../lib/db/schema";
import type { ExecutionEventMetadata } from "../lib/ralph/types";
import { eq, sql } from "drizzle-orm";
import { canExecuteTask, recordUsage } from "../lib/billing";
import { runLoop, type LoopContext, type ExecutionMode } from "../lib/ralph";
import {
  TestGate,
  parseTestOutput,
  type TestGatePolicy,
} from "../lib/ralph/test-gate";
import { getFeatureFlag } from "../lib/config/feature-flags";
import {
  createExecutionWorker,
  createAutonomousFlowWorker,
  createBrainstormWorker,
  createPlanWorker,
  type ExecutionJobData,
  type ExecutionJobResult,
  type BrainstormJobData,
  type BrainstormJobResult,
  type PlanJobData,
  type PlanJobResult,
} from "../lib/queue";
import { decryptGithubToken } from "../lib/crypto";
import { getAIClientConfig } from "../lib/api";
import {
  createAIClient,
  generatePlan,
  generateInitialBrainstorm,
  type RepoContext,
} from "../lib/ai";
import { scanRepoViaGitHub } from "../lib/github/repo-scanner";
import {
  pushBranch,
  buildAuthenticatedUrl,
  hasUncommittedChanges,
  getHeadSha,
} from "../lib/ralph/git-operations";
import { createPullRequest } from "../lib/github/client";
import { createPendingChanges } from "../lib/db/pending-changes";
import { createTestRun, completeTestRun } from "../lib/db/test-runs";
import { detectTestCommand } from "../lib/ralph/test-detector";
import { runTests, getTestStatus } from "../lib/ralph/test-runner";
import {
  generateDiff,
  type FileChange,
  detectAction,
} from "../lib/ralph/diff-generator";
import {
  publishWorkerEvent,
  createWorkerUpdateEvent,
  publishProcessingEvent,
  createProcessingEvent,
  publishExecutionEvent,
  phaseStatusMessages,
} from "../lib/workers/events";
import simpleGit from "simple-git";
import { createDomainEvent } from "../lib/domain-events/bus";
import { initDomainEventSystem } from "../lib/application/event-system";
import { publishForJob } from "../lib/application/event-handlers";
import path from "path";
import fs from "fs/promises";
import { workerLogger } from "../lib/logger";

const REPOS_DIR = process.env.REPOS_DIR || "/app/repos";

// Determine execution mode from environment or default to multi-agent
const EXECUTION_MODE: ExecutionMode =
  (process.env.EXECUTION_MODE as ExecutionMode) || "multi-agent";

// Parse boolean environment variable
function parseBoolean(
  value: string | undefined,
  defaultValue: boolean,
): boolean {
  if (value === undefined) return defaultValue;
  const normalized = value.toLowerCase().trim();
  return (
    normalized === "true" ||
    normalized === "1" ||
    normalized === "yes" ||
    normalized === "on"
  );
}

// Build PR description from task and execution result
function buildPRDescription(
  taskTitle: string,
  taskDescription: string,
  result: { iterations: number; commits?: string[]; error?: string },
): string {
  const lines: string[] = [
    "## Summary",
    "",
    `This PR implements: **${taskTitle}**`,
    "",
  ];

  if (taskDescription) {
    lines.push(taskDescription, "");
  }

  lines.push("## Changes");
  lines.push("");
  lines.push(`- Completed in ${result.iterations} iteration(s)`);
  if (result.commits && result.commits.length > 0) {
    lines.push(`- ${result.commits.length} commit(s) made`);
  }
  lines.push("");

  lines.push("## Test Plan");
  lines.push("");
  lines.push("- [ ] Verify the changes work as expected");
  lines.push("- [ ] Run existing tests");
  lines.push("- [ ] Manual testing completed");
  lines.push("");

  lines.push("---");
  lines.push("*Generated by [LoopForge](https://loopforge.dev)*");

  return lines.join("\n");
}

// Centralized error handling for execution failures
async function handleExecutionFailure(
  error: Error | string,
  context: {
    executionId: string;
    taskId: string;
    userId: string;
    workerJobId?: string;
    repoName?: string;
    taskTitle?: string;
  },
): Promise<void> {
  const errorMessage = error instanceof Error ? error.message : error;

  workerLogger.error(
    { ...context, error: errorMessage },
    "Execution failure - updating all records",
  );

  // Update execution status
  await db
    .update(executions)
    .set({
      status: "failed",
      completedAt: new Date(),
      errorMessage,
    })
    .where(eq(executions.id, context.executionId));

  // Update task status with history
  await db
    .update(tasks)
    .set({
      status: "stuck",
      statusHistory: buildStatusHistoryAppend({
        fromStatus: "executing",
        toStatus: "stuck",
        triggeredBy: "worker",
      }),
      processingPhase: null,
      processingJobId: null,
      processingStartedAt: null,
      processingStatusText: null,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, context.taskId));

  // Update worker job if we have one
  if (context.workerJobId) {
    await db
      .update(workerJobs)
      .set({
        status: "failed",
        completedAt: new Date(),
        errorMessage,
      })
      .where(eq(workerJobs.id, context.workerJobId));

    // Emit error event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: context.workerJobId,
      eventType: "error",
      content: errorMessage,
    });
  }

  // Publish error event to Redis for SSE
  if (context.repoName && context.taskTitle) {
    const errorEvent = createWorkerUpdateEvent(
      context.taskId,
      context.taskTitle,
      context.repoName,
      "stuck",
      {
        currentAction: "Execution failed",
        error: errorMessage,
        completedAt: new Date(),
      },
    );
    await publishWorkerEvent(context.userId, errorEvent);
  }
}

// Database-compatible event types
type DbEventType =
  | "thinking"
  | "file_read"
  | "file_write"
  | "command_run"
  | "commit"
  | "error"
  | "complete"
  | "stuck"
  // Setup phase events
  | "setup_start"
  | "repo_clone"
  | "repo_update"
  | "branch_create"
  | "branch_checkout"
  | "setup_complete";

// Map extended event types to database-compatible types
function mapEventTypeToDb(eventType: string): DbEventType {
  const mapping: Record<string, DbEventType> = {
    // Direct mappings
    thinking: "thinking",
    file_read: "file_read",
    file_write: "file_write",
    command_run: "command_run",
    commit: "commit",
    error: "error",
    complete: "complete",
    stuck: "stuck",
    // Setup phase events
    setup_start: "setup_start",
    repo_clone: "repo_clone",
    repo_update: "repo_update",
    branch_create: "branch_create",
    branch_checkout: "branch_checkout",
    setup_complete: "setup_complete",
    // Map new event types to existing ones
    agent_start: "thinking",
    agent_complete: "thinking",
    review_start: "thinking",
    review_complete: "thinking",
    task_start: "thinking",
    task_complete: "complete",
    task_failed: "error",
  };

  return mapping[eventType] || "thinking";
}

// Worker event types for unified history
type WorkerEventTypeValue =
  | "thinking"
  | "action"
  | "file_read"
  | "file_write"
  | "api_call"
  | "error"
  | "complete";

// Map execution event types to worker event types
function mapEventTypeToWorkerEvent(eventType: string): WorkerEventTypeValue {
  const mapping: Record<string, WorkerEventTypeValue> = {
    thinking: "thinking",
    file_read: "file_read",
    file_write: "file_write",
    command_run: "action",
    commit: "action",
    error: "error",
    complete: "complete",
    stuck: "error",
    agent_start: "thinking",
    agent_complete: "complete",
    review_start: "thinking",
    review_complete: "complete",
    task_start: "action",
    task_complete: "complete",
    task_failed: "error",
  };

  return mapping[eventType] || "action";
}

// Format event type for display in SSE stream
function formatEventAction(eventType: string, content?: string): string {
  const actionMap: Record<string, string> = {
    thinking: "Analyzing...",
    file_read: "Reading file",
    file_write: "Writing file",
    command_run: "Running command",
    commit: "Committing changes",
    error: "Error encountered",
    complete: "Completed",
    stuck: "Failed",
    agent_start: "Starting agent",
    agent_complete: "Agent finished",
    review_start: "Starting review",
    review_complete: "Review finished",
    task_start: "Starting task",
    task_complete: "Task completed",
    task_failed: "Task failed",
    // Setup phase events
    setup_start: "Starting setup",
    repo_clone: "Cloning repository",
    repo_update: "Updating repository",
    branch_create: "Creating branch",
    branch_checkout: "Checking out branch",
    setup_complete: "Setup complete",
  };

  const action = actionMap[eventType] || "Processing...";

  // Add content snippet if available (truncate for display)
  if (content && content.length > 0) {
    const snippet = content.slice(0, 50).replace(/\n/g, " ");
    return `${action}: ${snippet}${content.length > 50 ? "..." : ""}`;
  }

  return action;
}

// Calculate execution progress based on phase, iteration and event type
// Setup phase: 0-20%, Execution phase: 20-95%, Complete: 100%
function calculateExecutionProgress(
  phase: "setup" | "execution",
  iteration: number,
  maxIterations: number,
  eventType: string,
): number {
  // Complete events get 100%
  if (eventType === "complete" || eventType === "task_complete") {
    return 100;
  }

  // Setup phase progress (0-20%)
  if (phase === "setup") {
    const setupProgress: Record<string, number> = {
      setup_start: 2,
      repo_clone: 5,
      repo_update: 8,
      branch_create: 15,
      branch_checkout: 15,
      setup_complete: 20,
    };
    return setupProgress[eventType] || 10;
  }

  // Execution phase progress (20-95%)
  const executionBase = 20;
  const executionRange = 75; // 95 - 20

  // Error/stuck events stay at current progress
  if (
    eventType === "error" ||
    eventType === "stuck" ||
    eventType === "task_failed"
  ) {
    return executionBase + (iteration / maxIterations) * executionRange * 0.9;
  }

  // Calculate progress within execution phase (20% to 95%)
  const iterationProgress = Math.min(iteration / maxIterations, 1);
  return Math.min(executionBase + iterationProgress * executionRange, 95);
}

// Build authenticated clone URL with GitHub token
function buildAuthenticatedCloneUrl(cloneUrl: string, token: string): string {
  const url = new URL(cloneUrl);
  url.username = "x-access-token";
  url.password = token;
  return url.toString();
}

// Get user's decrypted GitHub token
async function getUserGithubToken(userId: string): Promise<string | null> {
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });

  if (!user?.encryptedGithubToken || !user?.githubTokenIv) {
    return null;
  }

  try {
    return decryptGithubToken({
      encrypted: user.encryptedGithubToken,
      iv: user.githubTokenIv,
    });
  } catch (error) {
    workerLogger.error({ error }, "Failed to decrypt GitHub token");
    return null;
  }
}

// Ensure target branch exists, creating from default branch if needed
async function ensureBranchExists(
  repoPath: string,
  targetBranch: string,
  defaultBranch: string,
  githubToken: string | null,
): Promise<{ created: boolean }> {
  const git = simpleGit(repoPath);

  // Fetch all remote branches
  await git.fetch("origin");

  // Check if target branch exists on remote
  const remotes = await git.branch(["-r"]);
  const remoteBranchExists = remotes.all.includes(`origin/${targetBranch}`);

  if (remoteBranchExists) {
    // Branch exists, checkout and pull
    workerLogger.info({ targetBranch }, "Branch exists, checking out");
    await git.checkout(targetBranch);
    await git.pull("origin", targetBranch);
    return { created: false };
  } else {
    // Branch doesn't exist, create from default branch
    workerLogger.info(
      { targetBranch, defaultBranch },
      "Branch does not exist, creating from default",
    );

    // First checkout default branch and pull latest
    await git.checkout(defaultBranch);
    await git.pull("origin", defaultBranch);

    // Create new branch from default (don't push yet - wait until we have commits)
    await git.checkoutLocalBranch(targetBranch);
    workerLogger.info(
      { targetBranch },
      "Created local branch (will push when commits are made)",
    );

    return { created: true };
  }
}

// Clone or update repository
async function cloneOrUpdateRepo(
  cloneUrl: string,
  repoName: string,
  targetBranch: string,
  defaultBranch: string,
  githubToken: string | null,
): Promise<{ repoPath: string; branchCreated: boolean }> {
  const repoPath = path.join(REPOS_DIR, repoName);

  // Use authenticated URL if token available
  const effectiveCloneUrl = githubToken
    ? buildAuthenticatedCloneUrl(cloneUrl, githubToken)
    : cloneUrl;

  // Ensure repos directory exists
  await fs.mkdir(REPOS_DIR, { recursive: true });

  const git = simpleGit();

  // Check if repo already exists
  let repoExists = false;
  try {
    await fs.access(repoPath);
    repoExists = true;
  } catch {
    repoExists = false;
  }

  if (repoExists) {
    // Repo exists, fetch latest
    workerLogger.info({ repoPath }, "Repository exists, fetching latest");
    const repoGit = simpleGit(repoPath);
    await repoGit.fetch("origin");
  } else {
    // Clone from default branch first (always succeeds)
    workerLogger.info({ repoName, defaultBranch }, "Cloning repository");
    await git.clone(effectiveCloneUrl, repoPath, ["--branch", defaultBranch]);
  }

  // Now ensure target branch exists (creates if needed)
  const { created } = await ensureBranchExists(
    repoPath,
    targetBranch,
    defaultBranch,
    githubToken,
  );

  return { repoPath, branchCreated: created };
}

// =============================================================================
// Pre-flight Checks
// =============================================================================

interface PreFlightResult {
  passed: boolean;
  repoIndexData: RepoIndex | null;
  warnings: string[];
  errors: string[];
}

/**
 * Run pre-flight checks before execution begins
 * - Verifies repo is cloned (or uses execution's clone)
 * - Checks indexing status
 * - Loads repo context for enhanced execution
 */
async function runPreFlightChecks(
  repoId: string,
  repoPath: string,
): Promise<PreFlightResult> {
  const warnings: string[] = [];
  const errors: string[] = [];

  // Check if repo path exists
  try {
    await fs.access(repoPath);
  } catch {
    errors.push(`Repository path does not exist: ${repoPath}`);
    return { passed: false, repoIndexData: null, warnings, errors };
  }

  // Check if it's a valid git repo
  const git = simpleGit(repoPath);
  const isRepo = await git.checkIsRepo();
  if (!isRepo) {
    errors.push(`Path is not a valid git repository: ${repoPath}`);
    return { passed: false, repoIndexData: null, warnings, errors };
  }

  // Check repo indexing status
  const repo = await db.query.repos.findFirst({
    where: eq(repos.id, repoId),
  });

  if (!repo) {
    errors.push("Repository not found in database");
    return { passed: false, repoIndexData: null, warnings, errors };
  }

  // Load repo index if available
  let repoIndexData: RepoIndex | null = null;

  if (repo.indexingStatus === "indexed") {
    repoIndexData =
      (await db.query.repoIndex.findFirst({
        where: eq(repoIndex.repoId, repoId),
      })) || null;

    if (repoIndexData) {
      workerLogger.info(
        {
          repoId,
          fileCount: repoIndexData.fileCount,
          techStack: repoIndexData.techStack,
        },
        "Loaded repo index for enhanced context",
      );
    }
  } else if (
    repo.indexingStatus === "pending" ||
    repo.indexingStatus === "indexing"
  ) {
    warnings.push(
      `Repository indexing is ${repo.indexingStatus} - execution will proceed without index context`,
    );
  } else if (repo.indexingStatus === "failed") {
    warnings.push(
      "Repository indexing failed - execution will proceed without index context",
    );
  }

  return { passed: true, repoIndexData, warnings, errors };
}

/**
 * Verify that actual work was completed
 * - Files were written
 * - Commits were made
 * - No phantom completions
 */
function verifyExecutionCompleted(
  result: { status: string; commits: string[]; iterations: number },
  filesWritten: number,
): { verified: boolean; reason?: string } {
  // Check if agent reported completion
  if (result.status !== "complete") {
    return { verified: true }; // Not claiming completion, no verification needed
  }

  // Verify actual work was done
  if (result.commits.length === 0) {
    return {
      verified: false,
      reason: "Agent reported completion but no commits were made",
    };
  }

  if (filesWritten === 0) {
    return {
      verified: false,
      reason: "Agent reported completion but no files were written",
    };
  }

  // Additional sanity check: at least one commit per iteration seems reasonable
  // but don't be too strict here
  workerLogger.info(
    {
      commits: result.commits.length,
      filesWritten,
      iterations: result.iterations,
    },
    "Execution verification passed",
  );

  return { verified: true };
}

/**
 * Notify dependent tasks when a blocker task fails
 * Creates activity events for tasks that are blocked by the failed task
 */
async function handleCascadingFailure(
  failedTaskId: string,
  failedTaskTitle: string,
  userId: string,
  repoId: string,
): Promise<void> {
  workerLogger.info(
    { failedTaskId },
    "Checking for cascading failure notifications",
  );

  try {
    // Find tasks that are blocked by the failed task
    const dependentTasks = await db.query.taskDependencies.findMany({
      where: eq(taskDependencies.blockedById, failedTaskId),
      with: {
        task: {
          columns: { id: true, title: true, status: true },
        },
      },
    });

    if (dependentTasks.length === 0) {
      workerLogger.debug({ failedTaskId }, "No dependent tasks found");
      return;
    }

    workerLogger.info(
      { failedTaskId, dependentCount: dependentTasks.length },
      "Notifying dependent tasks of blocker failure",
    );

    // Create activity events for each dependent task
    for (const dep of dependentTasks) {
      await db.insert(activityEvents).values({
        id: crypto.randomUUID(),
        taskId: dep.task.id,
        repoId,
        userId,
        eventType: "blocker_failed",
        eventCategory: "system" as ActivityEventCategory,
        title: "Blocker task failed",
        content: `Blocked by "${failedTaskTitle}" which has failed. This task cannot proceed until the blocker is resolved.`,
        metadata: {
          failedBlockerId: failedTaskId,
          failedBlockerTitle: failedTaskTitle,
        },
        createdAt: new Date(),
      });

      workerLogger.debug(
        { dependentTaskId: dep.task.id, failedBlockerId: failedTaskId },
        "Created blocker_failed activity event",
      );
    }
  } catch (err) {
    workerLogger.error(
      { failedTaskId, error: err },
      "Error in cascading failure handling",
    );
    // Don't throw - failure notification shouldn't fail the main task processing
  }
}

/**
 * Handle task auto-orchestration when a task completes
 * Finds tasks blocked by this one and triggers execution if:
 * 1. All their blockers are now complete
 * 2. autoExecuteWhenUnblocked is enabled
 */
async function handleTaskOrchestration(
  completedTaskId: string,
  userId: string,
): Promise<void> {
  workerLogger.info({ completedTaskId }, "Checking for orchestration triggers");

  try {
    // Find tasks that are blocked by the completed task
    const dependentTasks = await db.query.taskDependencies.findMany({
      where: eq(taskDependencies.blockedById, completedTaskId),
      with: {
        task: {
          with: {
            repo: true,
          },
        },
      },
    });

    workerLogger.info(
      { completedTaskId, dependentCount: dependentTasks.length },
      "Found dependent tasks",
    );

    for (const dep of dependentTasks) {
      const task = dep.task;

      // Skip if already done or executing
      if (task.status === "done" || task.status === "executing") {
        workerLogger.debug(
          { taskId: task.id, status: task.status },
          "Skipping task - already done or executing",
        );
        continue;
      }

      // Skip if auto-execute not enabled
      if (!task.autoExecuteWhenUnblocked) {
        workerLogger.debug(
          { taskId: task.id },
          "Skipping task - auto-execute not enabled",
        );
        continue;
      }

      // Check if ALL blockers are complete
      const allBlockers = await db.query.taskDependencies.findMany({
        where: eq(taskDependencies.taskId, task.id),
        with: {
          blockedBy: {
            columns: { status: true, id: true },
          },
        },
      });

      const allBlockersComplete = allBlockers.every(
        (b) => b.blockedBy.status === "done",
      );

      if (!allBlockersComplete) {
        workerLogger.debug(
          { taskId: task.id },
          "Skipping task - not all blockers complete",
        );
        continue;
      }

      // All blockers complete and auto-execute enabled - trigger execution!
      workerLogger.info(
        { taskId: task.id, title: task.title },
        "Auto-triggering task execution (all blockers complete)",
      );

      // Log activity event
      await db.insert(activityEvents).values({
        id: crypto.randomUUID(),
        taskId: task.id,
        repoId: task.repoId,
        userId,
        eventType: "task_auto_triggered",
        eventCategory: "system" as ActivityEventCategory,
        title: `Auto-triggered: ${task.title}`,
        content: `Task automatically queued for execution after all blockers completed`,
        metadata: {
          completedBlockerId: completedTaskId,
          blockerCount: allBlockers.length,
        },
        createdAt: new Date(),
      });

      // Update task status to ready (if not already past planning)
      if (
        task.status === "todo" ||
        task.status === "brainstorming" ||
        task.status === "planning"
      ) {
        // Task isn't ready for execution yet - update to ready if it has a plan
        if (task.planContent) {
          await db
            .update(tasks)
            .set({
              status: "ready",
              statusHistory: buildStatusHistoryAppend({
                fromStatus: task.status,
                toStatus: "ready",
                triggeredBy: "autonomous",
              }),
              updatedAt: new Date(),
            })
            .where(eq(tasks.id, task.id));

          workerLogger.info(
            { taskId: task.id },
            "Task marked as ready for auto-execution",
          );
        } else {
          workerLogger.info(
            { taskId: task.id },
            "Task unblocked but needs planning first",
          );
        }
      } else if (task.status === "ready") {
        // Task is ready - queue for execution
        // Get user's API settings
        const user = await db.query.users.findFirst({
          where: eq(users.id, userId),
        });

        if (!user) {
          workerLogger.warn(
            { taskId: task.id, userId },
            "Cannot auto-execute: user not found",
          );
          continue;
        }

        // Resolve AI config on demand (never store plaintext keys in Redis)
        const autoExecConfig = getAIClientConfig(user);
        if (!autoExecConfig) {
          workerLogger.warn(
            { taskId: task.id, userId },
            "Cannot auto-execute: no AI provider configured",
          );
          continue;
        }

        // Create execution record
        const [execution] = await db
          .insert(executions)
          .values({
            taskId: task.id,
            status: "queued",
            iteration: 0,
          })
          .returning();

        // Update task to executing
        await db
          .update(tasks)
          .set({
            status: "executing",
            statusHistory: buildStatusHistoryAppend({
              fromStatus: "ready",
              toStatus: "executing",
              triggeredBy: "autonomous",
            }),
            processingPhase: "executing",
            processingJobId: execution.id,
            processingStartedAt: new Date(),
            processingStatusText: "Auto-execution starting...",
            updatedAt: new Date(),
          })
          .where(eq(tasks.id, task.id));

        // Build dependency context for the AI agent
        let enhancedPlan = task.planContent!;
        try {
          const completedBlocker = await db.query.tasks.findFirst({
            where: eq(tasks.id, completedTaskId),
            with: {
              executions: {
                limit: 1,
                orderBy: (e, { desc }) => [desc(e.createdAt)],
              },
            },
          });
          if (completedBlocker) {
            const blockerSummary = [
              `\n\n---`,
              `## Dependency Context`,
              `This task was auto-triggered after its blocker task completed.`,
              ``,
              `**Blocker task:** ${completedBlocker.title}`,
              completedBlocker.description
                ? `**Blocker description:** ${completedBlocker.description}`
                : null,
              completedBlocker.executions?.[0]?.commits?.length
                ? `**Blocker commits:** ${completedBlocker.executions[0].commits.join(", ")}`
                : null,
              ``,
              `Take into account what was changed by the blocker task when implementing this task.`,
              `---\n`,
            ]
              .filter(Boolean)
              .join("\n");
            enhancedPlan = enhancedPlan + blockerSummary;
          }
        } catch (depCtxErr) {
          workerLogger.warn(
            { error: depCtxErr },
            "Failed to build dependency context - proceeding without it",
          );
        }

        const bus = initDomainEventSystem();
        const queuedExecution = await publishForJob(
          bus,
          createDomainEvent("TaskExecutionRequested", {
            executionId: execution.id,
            taskId: task.id,
            repoId: task.repoId,
            userId,
            aiProvider: autoExecConfig.provider,
            preferredModel: autoExecConfig.model,
            planContent: enhancedPlan,
            branch: task.branch || `loopforge/${task.id.slice(0, 8)}`,
            defaultBranch: task.repo.defaultBranch || "main",
            cloneUrl: task.repo.cloneUrl,
          }),
        );

        if (!queuedExecution || !queuedExecution.id) {
          throw new Error("Failed to queue auto-execution job");
        }

        workerLogger.info(
          { taskId: task.id, executionId: execution.id },
          "Auto-execution queued with dependency context",
        );
      }
    }
  } catch (err) {
    workerLogger.error(
      { completedTaskId, error: err },
      "Error in task orchestration",
    );
    // Don't throw - orchestration failure shouldn't fail the main task
  }
}

/**
 * Build enhanced loop context with repo index data
 */
function buildEnhancedContext(
  baseContext: LoopContext,
  repoIndexData: RepoIndex | null,
): LoopContext {
  if (!repoIndexData) {
    return baseContext;
  }

  // Add tech stack info to constraints
  const techStackInfo: string[] = [];

  if (repoIndexData.techStack) {
    const { languages, frameworks, buildTools } = repoIndexData.techStack;
    if (languages?.length) {
      techStackInfo.push(`Languages: ${languages.join(", ")}`);
    }
    if (frameworks?.length) {
      techStackInfo.push(`Frameworks: ${frameworks.join(", ")}`);
    }
    if (buildTools?.length) {
      techStackInfo.push(`Build tools: ${buildTools.join(", ")}`);
    }
  }

  // Add entry points info
  if (repoIndexData.entryPoints?.length) {
    const entryPointPaths = repoIndexData.entryPoints
      .filter((ep) => ep.type === "entry" || ep.type === "main")
      .map((ep) => ep.path)
      .slice(0, 5);
    if (entryPointPaths.length > 0) {
      techStackInfo.push(`Entry points: ${entryPointPaths.join(", ")}`);
    }
  }

  // Enhance do constraints with repo context
  const enhancedDoConstraints = [
    ...baseContext.doConstraints,
    ...techStackInfo.map((info) => `Repository context: ${info}`),
  ];

  return {
    ...baseContext,
    doConstraints: enhancedDoConstraints,
  };
}

async function processExecution(
  job: Job<ExecutionJobData, ExecutionJobResult>,
): Promise<ExecutionJobResult> {
  const {
    executionId,
    taskId,
    userId,
    aiProvider,
    preferredModel,
    planContent,
    branch,
    defaultBranch,
    cloneUrl,
  } = job.data;

  // Check billing limits for managed users
  const billingCheck = await canExecuteTask(userId);
  if (!billingCheck.allowed) {
    workerLogger.warn(
      { userId, reason: billingCheck.reason },
      "Execution blocked by billing limits",
    );
    throw new Error(`Billing limit exceeded: ${billingCheck.reason}`);
  }

  // Skills Framework Integration - Initialize skills system
  const skillsEnabled = process.env.ENABLE_SKILLS_SYSTEM !== "false";
  if (skillsEnabled) {
    try {
      const { initializeSkills, isSkillsSystemEnabled } =
        await import("../lib/skills");

      if (isSkillsSystemEnabled()) {
        initializeSkills();
        workerLogger.info("Skills system initialized for execution");
      }
    } catch (error) {
      // Skills framework optional - don't fail execution if not available
      workerLogger.warn("Skills framework not available:", error);
    }
  }

  // Track token usage for this execution
  let totalInputTokens = 0;
  let totalOutputTokens = 0;

  // Decrypt API key on demand from user record (never stored in Redis job data)
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });
  if (!user) {
    throw new Error("User not found");
  }
  const aiConfig = getAIClientConfig(user);
  if (!aiConfig) {
    throw new Error("No AI provider configured for user");
  }

  // Create AI client with the decrypted key
  const aiClient = await createAIClient(
    aiProvider,
    aiConfig.apiKey,
    preferredModel,
  );

  // Update execution status to running
  await db
    .update(executions)
    .set({ status: "running", startedAt: new Date() })
    .where(eq(executions.id, executionId));

  // Get task details
  const task = await db.query.tasks.findFirst({
    where: eq(tasks.id, taskId),
    with: { repo: true },
  });

  if (!task) {
    throw new Error("Task not found");
  }

  // Create worker job record for execution phase
  const [workerJob] = await db
    .insert(workerJobs)
    .values({
      taskId,
      phase: "executing",
      status: "running",
      startedAt: new Date(),
      jobId: job.id,
    })
    .returning();

  const bus = initDomainEventSystem();
  await bus.publish(
    createDomainEvent("ExecutionStarted", {
      executionId,
      taskId,
      repoId: task.repoId,
      userId,
    }),
  );

  // Track stats for result summary
  let filesWritten = 0;
  let commandsRun = 0;

  try {
    // === SETUP PHASE (now inside try-catch!) ===

    // Helper to emit setup events to both executionEvents and workerEvents
    const emitSetupEvent = async (
      eventType: DbEventType,
      content: string,
      metadata: Record<string, unknown> = {},
    ) => {
      // Store in executionEvents for activity feed
      await db.insert(executionEvents).values({
        id: crypto.randomUUID(),
        executionId,
        eventType: mapEventTypeToDb(eventType),
        content,
        metadata: { ...metadata, phase: "setup" },
        createdAt: new Date(),
      });

      // Publish to SSE for real-time streaming
      await publishExecutionEvent(executionId, {
        type: mapEventTypeToDb(eventType),
        content,
        metadata: { ...metadata, phase: "setup" },
      });

      // Store in workerEvents for worker history
      await db.insert(workerEvents).values({
        workerJobId: workerJob.id,
        eventType:
          eventType === "setup_start" || eventType === "setup_complete"
            ? "thinking"
            : "action",
        content,
        metadata: { ...metadata, phase: "setup" } as WorkerEventMetadata,
      });
    };

    // Emit setup start event
    await emitSetupEvent("setup_start", "Starting setup phase...", {
      model: preferredModel,
    });

    // Update job progress for setup phase (0-20%)
    await job.updateProgress({
      iteration: 0,
      lastEvent: "setup_start",
      progressPercent: 2,
    });

    // Publish setup start to SSE
    const setupStartEvent = createWorkerUpdateEvent(
      taskId,
      task.title,
      task.repo.name,
      "executing",
      {
        currentStep: "Setup",
        currentAction: "Preparing execution environment...",
      },
    );
    setupStartEvent.data.progress = 2;
    await publishWorkerEvent(userId, setupStartEvent);

    // Get user's GitHub token for authenticated git operations
    const githubToken = await getUserGithubToken(userId);

    // Clone or update the repository
    workerLogger.info(
      { repo: task.repo.fullName },
      "Cloning/updating repository",
    );

    // Emit repo clone event
    await emitSetupEvent(
      "repo_clone",
      `Cloning repository: ${task.repo.fullName}`,
      {
        repo: task.repo.fullName,
      },
    );

    await job.updateProgress({
      iteration: 0,
      lastEvent: "repo_clone",
      progressPercent: 5,
    });

    const repoCloneEvent = createWorkerUpdateEvent(
      taskId,
      task.title,
      task.repo.name,
      "executing",
      {
        currentStep: "Setup",
        currentAction: `Cloning repository: ${task.repo.fullName}`,
      },
    );
    repoCloneEvent.data.progress = 5;
    await publishWorkerEvent(userId, repoCloneEvent);

    const { repoPath, branchCreated } = await cloneOrUpdateRepo(
      cloneUrl,
      task.repo.fullName.replace("/", "_"), // Sanitize path
      branch,
      defaultBranch || task.repo.defaultBranch || "main",
      githubToken,
    );
    workerLogger.info({ repoPath, branchCreated }, "Repository ready");

    // Emit branch event
    const branchEventType = branchCreated ? "branch_create" : "branch_checkout";
    const branchAction = branchCreated
      ? `Created branch: ${branch}`
      : `Checked out branch: ${branch}`;

    await emitSetupEvent(branchEventType, branchAction, {
      branch,
      branchCreated,
    });

    await job.updateProgress({
      iteration: 0,
      lastEvent: branchEventType,
      progressPercent: 15,
    });

    const branchEvent = createWorkerUpdateEvent(
      taskId,
      task.title,
      task.repo.name,
      "executing",
      {
        currentStep: "Setup",
        currentAction: branchAction,
      },
    );
    branchEvent.data.progress = 15;
    await publishWorkerEvent(userId, branchEvent);

    // === PRE-FLIGHT CHECKS ===
    await emitSetupEvent("thinking", "Running pre-flight checks...");

    const preFlightResult = await runPreFlightChecks(task.repo.id, repoPath);

    // Log warnings
    for (const warning of preFlightResult.warnings) {
      workerLogger.warn(
        { repoId: task.repo.id, warning },
        "Pre-flight warning",
      );
      await emitSetupEvent("thinking", `Warning: ${warning}`);
    }

    // Check for errors (non-fatal - we continue but log)
    if (!preFlightResult.passed) {
      for (const error of preFlightResult.errors) {
        workerLogger.error(
          { repoId: task.repo.id, error },
          "Pre-flight check failed",
        );
        await emitSetupEvent("error", `Pre-flight error: ${error}`);
      }
      // For now, continue execution even if pre-flight fails
      // The errors are logged and visible in the timeline
    }

    await job.updateProgress({
      iteration: 0,
      lastEvent: "preflight_complete",
      progressPercent: 18,
    });

    // Emit setup complete event
    await emitSetupEvent(
      "setup_complete",
      "Setup complete, starting execution...",
    );

    await job.updateProgress({
      iteration: 0,
      lastEvent: "setup_complete",
      progressPercent: 20,
    });

    const setupCompleteEvent = createWorkerUpdateEvent(
      taskId,
      task.title,
      task.repo.name,
      "executing",
      {
        currentStep: "Setup",
        currentAction: "Setup complete, starting execution...",
      },
    );
    setupCompleteEvent.data.progress = 20;
    await publishWorkerEvent(userId, setupCompleteEvent);

    // === END SETUP PHASE ===

    // Create base loop context
    const baseLoopContext: LoopContext = {
      project: task.repo.name,
      changeId: task.id.slice(0, 8),
      workingDir: repoPath,
      tasksPath: path.join(repoPath, "tasks.md"),
      quickVerify: "echo 'Quick verify'",
      fullVerify: "echo 'Full verify'",
      doConstraints: [
        "Follow the plan steps exactly",
        "Make small, focused changes",
        "Write tests when appropriate",
      ],
      dontConstraints: [
        "Don't deviate from the plan",
        "Don't make unrelated changes",
        "Don't skip verification",
      ],
      // Include plan content for multi-agent mode
      planContent,
    };

    // Enhance context with repo index data if available
    const loopContext = buildEnhancedContext(
      baseLoopContext,
      preFlightResult.repoIndexData,
    );

    // Determine which execution mode to use
    const useMultiAgent = EXECUTION_MODE === "multi-agent" && planContent;

    workerLogger.info(
      { mode: useMultiAgent ? "multi-agent" : "classic" },
      "Execution mode",
    );
    const result = await runLoop(loopContext, {
      client: aiClient,
      maxIterations: 50,
      stuckThreshold: 3,
      mode: useMultiAgent ? "multi-agent" : "classic",
      parallelOptions: {
        maxConcurrency: 3,
        retryOnFailure: true,
        stopOnCriticalFailure: true,
        mandatoryReview: true,
        maxRetries: 1,
      },
      onEvent: async (event) => {
        // Store event in database (map event type to db-compatible type)
        await db.insert(executionEvents).values({
          id: crypto.randomUUID(),
          executionId,
          eventType: mapEventTypeToDb(event.type),
          content: event.content,
          metadata: {
            ...event.metadata,
            // Store the original event type in metadata for reference
            originalEventType: event.type,
          },
          createdAt: event.timestamp,
        });

        // Publish to SSE for real-time streaming
        await publishExecutionEvent(executionId, {
          type: mapEventTypeToDb(event.type),
          content: event.content,
          metadata: {
            ...event.metadata,
            originalEventType: event.type,
          },
        });

        // Also insert to worker_events for unified history
        const workerEventType = mapEventTypeToWorkerEvent(event.type);
        await db.insert(workerEvents).values({
          workerJobId: workerJob.id,
          eventType: workerEventType,
          content: event.content,
          metadata: {
            ...event.metadata,
            iteration: event.metadata?.iteration,
          } as WorkerEventMetadata,
        });

        // Track stats
        if (event.type === "file_write") filesWritten++;
        if (event.type === "command_run") commandsRun++;

        // Track token usage if available in metadata
        const inputTokens = (event.metadata as Record<string, unknown>)
          ?.inputTokens as number | undefined;
        const outputTokens = (event.metadata as Record<string, unknown>)
          ?.outputTokens as number | undefined;
        if (inputTokens) totalInputTokens += inputTokens;
        if (outputTokens) totalOutputTokens += outputTokens;

        // Update job progress
        const iteration = event.metadata?.iteration || 0;
        await job.updateProgress({
          iteration,
          lastEvent: event.type,
          progressPercent: event.metadata?.progressPercent || 0,
          agentId: event.metadata?.agentId,
          taskId: event.metadata?.taskId,
        });

        // Publish to Redis for SSE streaming to Workers page
        const progress = calculateExecutionProgress(
          "execution",
          iteration,
          50,
          event.type,
        );
        const currentStep = event.metadata?.taskId
          ? `Step ${event.metadata.taskId}`
          : `Iteration ${iteration}`;

        const workerEvent = createWorkerUpdateEvent(
          taskId,
          task.title,
          task.repo.name,
          "executing",
          {
            currentStep,
            currentAction: formatEventAction(event.type, event.content),
          },
        );
        // Override the calculated progress with our execution-specific calculation
        workerEvent.data.progress = progress;

        await publishWorkerEvent(userId, workerEvent);
      },
      onProgress: async (progress) => {
        // Store progress updates
        await job.updateProgress({
          ...progress,
        });
      },
    });

    // === COMPLETION VERIFICATION ===
    const verification = verifyExecutionCompleted(result, filesWritten);

    if (!verification.verified) {
      workerLogger.warn(
        {
          taskId,
          reason: verification.reason,
          commits: result.commits.length,
          filesWritten,
        },
        "Execution completion verification failed",
      );

      // Override the result status to stuck if verification failed
      result.status = "stuck";
      result.error = verification.reason || "Execution verification failed";

      // Log the verification failure event
      await db.insert(executionEvents).values({
        id: crypto.randomUUID(),
        executionId,
        eventType: "stuck",
        content: `Verification failed: ${verification.reason}`,
        metadata: {
          commits: result.commits.length,
          filesWritten,
          originalStatus: "complete",
        },
        createdAt: new Date(),
      });
      await publishExecutionEvent(executionId, {
        type: "stuck",
        content: `Verification failed: ${verification.reason}`,
        metadata: {
          commits: result.commits.length,
          filesWritten,
          originalStatus: "complete",
        },
      });
    }

    // === P0: NEW REVIEW FLOW ===
    // If execution was successful, collect file changes and move to review status
    // instead of immediately committing and creating PR

    if (result.status === "complete") {
      workerLogger.info(
        { taskId, filesWritten },
        "Execution complete, collecting changes for review",
      );

      // Emit event for collecting changes
      await db.insert(executionEvents).values({
        executionId,
        eventType: "thinking",
        content: "Collecting file changes for review...",
        metadata: { phase: "review_prep" },
        createdAt: new Date(),
      });
      await publishExecutionEvent(executionId, {
        type: "thinking",
        content: "Collecting file changes for review...",
        metadata: { phase: "review_prep" },
      });

      // Collect file changes using git
      const git = simpleGit(repoPath);
      const fileChanges: FileChange[] = [];

      try {
        // Get list of changed files (staged and unstaged)
        const status = await git.status();
        const changedFiles = [
          ...status.modified.map((f) => ({
            path: f,
            status: "modified" as const,
          })),
          ...status.created.map((f) => ({
            path: f,
            status: "created" as const,
          })),
          ...status.not_added.map((f) => ({
            path: f,
            status: "created" as const,
          })),
          ...status.deleted.map((f) => ({
            path: f,
            status: "deleted" as const,
          })),
        ];

        workerLogger.info(
          { changedFilesCount: changedFiles.length },
          "Found changed files",
        );

        // Read content for each changed file
        for (const file of changedFiles) {
          try {
            let oldContent: string | null = null;
            let newContent = "";

            if (file.status === "deleted") {
              // For deleted files, get the old content from HEAD
              try {
                oldContent = await git.show([`HEAD:${file.path}`]);
              } catch {
                oldContent = "";
              }
              newContent = "";
            } else {
              // For created/modified files
              const fsPromises = await import("fs/promises");
              const filePath = path.join(repoPath, file.path);
              newContent = await fsPromises.readFile(filePath, "utf-8");

              if (file.status === "modified") {
                // Get old content from HEAD
                try {
                  oldContent = await git.show([`HEAD:${file.path}`]);
                } catch {
                  oldContent = null;
                }
              }
            }

            const action = detectAction(oldContent, newContent || null);
            fileChanges.push({
              filePath: file.path,
              action,
              oldContent,
              newContent: newContent || "",
            });
          } catch (fileErr) {
            workerLogger.warn(
              { file: file.path, error: fileErr },
              "Failed to read file content",
            );
          }
        }

        // Generate diffs and store pending changes
        if (fileChanges.length > 0) {
          const pendingChangeRecords = fileChanges.map((change) => {
            const diff = generateDiff(change);
            return {
              executionId,
              taskId,
              filePath: change.filePath,
              action: change.action,
              oldContent: change.oldContent,
              newContent: change.newContent,
              diffPatch: diff.patch,
              isApproved: false,
            };
          });

          await createPendingChanges(pendingChangeRecords);
          workerLogger.info(
            { count: pendingChangeRecords.length },
            "Stored pending changes for review",
          );

          await db.insert(executionEvents).values({
            executionId,
            eventType: "complete",
            content: `${pendingChangeRecords.length} file(s) ready for review`,
            metadata: { pendingChangesCount: pendingChangeRecords.length },
            createdAt: new Date(),
          });
          await publishExecutionEvent(executionId, {
            type: "complete",
            content: `${pendingChangeRecords.length} file(s) ready for review`,
            metadata: { pendingChangesCount: pendingChangeRecords.length },
          });
        }

        // === P0: OPTIONAL TEST EXECUTION ===
        let testsPassed: boolean | null = null;
        let testRunId: string | null = null;

        if (task.repo.testsEnabled !== false) {
          // Detect or use configured test command
          const testCommand =
            task.repo.testCommand ||
            (await detectTestCommand(repoPath)).recommended?.command;

          if (testCommand) {
            workerLogger.info({ testCommand }, "Running tests before review");

            await db.insert(executionEvents).values({
              executionId,
              eventType: "thinking",
              content: `Running tests: ${testCommand}`,
              metadata: { testCommand },
              createdAt: new Date(),
            });
            await publishExecutionEvent(executionId, {
              type: "thinking",
              content: `Running tests: ${testCommand}`,
              metadata: { testCommand },
            });

            // Create test run record
            const testRun = await createTestRun({
              executionId,
              taskId,
              command: testCommand,
              status: "running",
            });
            testRunId = testRun.id;

            // Run tests
            const testResult = await runTests({
              command: testCommand,
              cwd: repoPath,
              timeout: task.repo.testTimeout || 300000,
              onOutput: (data, stream) => {
                workerLogger.debug(
                  { stream, length: data.length },
                  "Test output",
                );
              },
            });

            // Update test run with results
            const testStatus = getTestStatus(testResult);
            await completeTestRun(testRun.id, {
              status: testStatus,
              exitCode: testResult.exitCode,
              stdout: testResult.stdout.slice(0, 50000), // Limit size
              stderr: testResult.stderr.slice(0, 50000),
              durationMs: testResult.durationMs,
            });

            testsPassed = testResult.success;

            await db.insert(executionEvents).values({
              executionId,
              eventType: testsPassed ? "complete" : "error",
              content: testsPassed
                ? `Tests passed in ${(testResult.durationMs / 1000).toFixed(1)}s`
                : `Tests failed (exit code: ${testResult.exitCode})`,
              metadata: {
                testStatus,
                durationMs: testResult.durationMs,
                exitCode: testResult.exitCode ?? undefined,
              },
              createdAt: new Date(),
            });
            await publishExecutionEvent(executionId, {
              type: testsPassed ? "complete" : "error",
              content: testsPassed
                ? `Tests passed in ${(testResult.durationMs / 1000).toFixed(1)}s`
                : `Tests failed (exit code: ${testResult.exitCode})`,
              metadata: {
                testStatus,
                durationMs: testResult.durationMs,
                exitCode: testResult.exitCode ?? undefined,
              },
            });

            workerLogger.info(
              { testsPassed, durationMs: testResult.durationMs },
              "Test execution complete",
            );
          } else {
            workerLogger.info("No test command detected, skipping tests");
          }
        }

        // Update execution status (completed but not yet approved)
        await db
          .update(executions)
          .set({
            status: "completed",
            iteration: result.iterations,
            completedAt: new Date(),
            commits: [], // No commits yet - will be set after approval
            errorMessage: null,
            branch,
          })
          .where(eq(executions.id, executionId));

        // Update task status to REVIEW (not done)
        const taskStatus: TaskStatus = "review";
        await db
          .update(tasks)
          .set({
            status: taskStatus,
            statusHistory: buildStatusHistoryAppend({
              fromStatus: "executing",
              toStatus: taskStatus,
              triggeredBy: "worker",
            }),
            processingPhase: null,
            processingJobId: null,
            processingStartedAt: null,
            processingStatusText: null,
            updatedAt: new Date(),
          })
          .where(eq(tasks.id, taskId));

        // === AUTO PR CREATION (OPTIONAL) ===
        // Create PR automatically if feature flag is enabled
        // PR is created but NOT merged (manual review required)
        const autoCreatePR = parseBoolean(
          process.env.ENABLE_AUTO_PR_CREATION,
          false,
        );

        if (autoCreatePR && testsPassed !== false && fileChanges.length > 0) {
          workerLogger.info(
            { taskId, filesChanged: fileChanges.length },
            "Auto-creating PR after successful execution",
          );

          try {
            const { getPendingChangesByTask } =
              await import("../lib/db/pending-changes");
            const { createExecutionCommit } =
              await import("../lib/db/execution-commits");
            const { buildPrContent, generateBranchName } =
              await import("../lib/github/pr-builder");
            const {
              commitAndPush,
              createFilesFromChanges,
              buildAuthenticatedUrl,
            } = await import("../lib/ralph/git-operations");
            const { createPullRequest } = await import("../lib/github/client");
            const { getLatestTestRun } = await import("../lib/db/test-runs");

            const pendingChanges = await getPendingChangesByTask(taskId);
            if (pendingChanges.length > 0) {
              const finalBranch = branch || generateBranchName(task);
              const githubToken = await getUserGithubToken(userId);

              if (githubToken) {
                // Create files from pending changes
                const filesChanged = await createFilesFromChanges(
                  repoPath,
                  pendingChanges,
                );

                // Commit and push
                const commitMessage = `[LoopForge] ${task.title}`;
                const remoteUrl = buildAuthenticatedUrl(
                  task.repo.cloneUrl,
                  githubToken,
                );
                const commitResult = await commitAndPush({
                  repoPath,
                  branch: finalBranch,
                  message: commitMessage,
                  files: filesChanged,
                  remoteUrl,
                });

                // Record the commit
                await createExecutionCommit({
                  executionId,
                  commitSha: commitResult.sha,
                  commitMessage,
                  filesChanged,
                });

                // Update execution with commit info
                await db
                  .update(executions)
                  .set({
                    commits: [commitResult.sha],
                    branch: finalBranch,
                  })
                  .where(eq(executions.id, executionId));

                // Create PR
                const testRun = await getLatestTestRun(taskId);
                const latestExecution = await db.query.executions.findFirst({
                  where: eq(executions.id, executionId),
                });

                const prContent = buildPrContent({
                  task,
                  repo: task.repo,
                  execution: latestExecution!,
                  testRun,
                  filesChanged,
                  commitMessages: [commitMessage],
                });

                const pr = await createPullRequest(githubToken, {
                  owner: task.repo.fullName.split("/")[0],
                  repo: task.repo.fullName.split("/")[1],
                  title: prContent.title,
                  body: prContent.body,
                  head: finalBranch,
                  base: task.repo.prTargetBranch || task.repo.defaultBranch,
                  draft: prContent.draft,
                });

                // Update task with PR info (but keep in review status)
                await db
                  .update(tasks)
                  .set({
                    prUrl: pr.html_url,
                    prNumber: pr.number,
                    updatedAt: new Date(),
                  })
                  .where(eq(tasks.id, taskId));

                workerLogger.info(
                  { prUrl: pr.html_url, prNumber: pr.number },
                  "PR created automatically - awaiting manual review before merge",
                );

                // Emit PR creation event
                await db.insert(executionEvents).values({
                  executionId,
                  eventType: "complete",
                  content: `Pull request created: ${pr.html_url}`,
                  metadata: { prUrl: pr.html_url, prNumber: pr.number },
                  createdAt: new Date(),
                });
              }
            }
          } catch (prError) {
            workerLogger.error(
              { error: prError, taskId },
              "Failed to auto-create PR - user can create manually",
            );

            // Don't fail the task - just log the error
            await db.insert(executionEvents).values({
              executionId,
              eventType: "error",
              content: `Auto PR creation failed: ${prError instanceof Error ? prError.message : "Unknown error"}. You can create the PR manually from the UI.`,
              metadata: { error: String(prError) },
              createdAt: new Date(),
            });
          }
        }

        // Emit completion event to worker_events
        await db.insert(workerEvents).values({
          workerJobId: workerJob.id,
          eventType: "complete",
          content: "Execution complete - awaiting review",
          metadata: {
            filesWritten,
            commandsRun,
            testsPassed,
            pendingChangesCount: fileChanges.length,
          } as WorkerEventMetadata,
        });

        // Update worker job as completed
        await db
          .update(workerJobs)
          .set({
            status: "completed",
            completedAt: new Date(),
            resultSummary: `${fileChanges.length} file${fileChanges.length !== 1 ? "s" : ""} ready for review${testsPassed !== null ? (testsPassed ? ", tests passed" : ", tests failed") : ""}`,
          })
          .where(eq(workerJobs.id, workerJob.id));

        // Publish review event to Redis for SSE
        const reviewEvent = createWorkerUpdateEvent(
          taskId,
          task.title,
          task.repo.name,
          "review",
          {
            currentAction: "Ready for review",
            completedAt: new Date(),
          },
        );
        await publishWorkerEvent(userId, reviewEvent);

        // === Test Gate: Enforce test policies ===
        let testGateBlocked = false;
        let testGateReason: string | undefined;

        if (getFeatureFlag("ENABLE_TEST_GATES") && testRunId && !testsPassed) {
          try {
            const testGatePolicy =
              (task.repo.testGatePolicy as TestGatePolicy) || "warn";
            const criticalTestPatterns =
              (task.repo.criticalTestPatterns as string[]) || [];

            // Get test run details
            const { getTestRunById } = await import("../lib/db/test-runs");
            const testRun = await getTestRunById(testRunId);

            if (testRun) {
              // Parse test output to extract results
              const testOutput = testRun.stdout || "";
              const testResult = parseTestOutput(testOutput);

              if (testResult) {
                const testGate = new TestGate({
                  policy: testGatePolicy,
                  criticalTestPatterns,
                  requireAllPassing: false,
                  allowedFailureRate: 0,
                });

                const gateDecision = testGate.analyze(testResult);

                if (gateDecision.shouldBlock) {
                  testGateBlocked = true;
                  testGateReason = gateDecision.reason;

                  workerLogger.warn(
                    { taskId, reason: testGateReason },
                    "Test gate blocked PR creation",
                  );

                  await db.insert(executionEvents).values({
                    executionId,
                    eventType: "error",
                    content: `Test gate blocked: ${testGateReason}`,
                    metadata:
                      gateDecision.metadata as unknown as ExecutionEventMetadata,
                    createdAt: new Date(),
                  });
                  await publishExecutionEvent(executionId, {
                    type: "error",
                    content: `Test gate blocked: ${testGateReason}`,
                    metadata: gateDecision.metadata,
                  });

                  // Update task with test gate failure info
                  await db
                    .update(tasks)
                    .set({
                      processingStatusText: `Tests failed: ${testGateReason}`,
                      updatedAt: new Date(),
                    })
                    .where(eq(tasks.id, taskId));
                }

                // Log warnings even if not blocking
                if (gateDecision.warnings && gateDecision.warnings.length > 0) {
                  workerLogger.info(
                    { taskId, warnings: gateDecision.warnings },
                    "Test gate warnings",
                  );
                }
              } else {
                workerLogger.warn({ taskId }, "Failed to parse test output");
              }
            }
          } catch (error) {
            workerLogger.error(
              { error, taskId },
              "Error during test gate analysis",
            );
          }
        }

        // === Auto-approve: skip review gate if repo has autoApprove enabled ===
        const canAutoApprove =
          !testGateBlocked &&
          task.repo.autoApprove &&
          (testsPassed === true || testsPassed === null);

        if (canAutoApprove) {
          workerLogger.info(
            { taskId, testsPassed },
            "Auto-approve enabled and tests passed (or skipped) - auto-approving changes",
          );

          try {
            const { getPendingChangesByTask, deletePendingChangesByTask } =
              await import("../lib/db/pending-changes");
            const { createExecutionCommit } =
              await import("../lib/db/execution-commits");
            const { buildPrContent, generateBranchName } =
              await import("../lib/github/pr-builder");
            const {
              commitAndPush,
              createFilesFromChanges,
              buildAuthenticatedUrl,
            } = await import("../lib/ralph/git-operations");
            const { createPullRequest } = await import("../lib/github/client");
            const { getLatestTestRun } = await import("../lib/db/test-runs");
            const pendingChanges = await getPendingChangesByTask(taskId);
            if (pendingChanges.length > 0) {
              const finalBranch = branch || generateBranchName(task);
              const githubToken = await getUserGithubToken(userId);

              if (githubToken) {
                // Create files from pending changes
                const filesChanged = await createFilesFromChanges(
                  repoPath,
                  pendingChanges,
                );

                // Commit and push
                const commitMessage = `[LoopForge] ${task.title}`;
                const remoteUrl = buildAuthenticatedUrl(
                  task.repo.cloneUrl,
                  githubToken,
                );
                const commitResult = await commitAndPush({
                  repoPath,
                  branch: finalBranch,
                  message: commitMessage,
                  files: filesChanged,
                  remoteUrl,
                });

                // Record the commit
                await createExecutionCommit({
                  executionId,
                  commitSha: commitResult.sha,
                  commitMessage,
                  filesChanged,
                });

                // Update execution with commit info
                await db
                  .update(executions)
                  .set({
                    commits: [commitResult.sha],
                    completedAt: new Date(),
                    status: "completed",
                  })
                  .where(eq(executions.id, executionId));

                // Create PR
                const testRun = await getLatestTestRun(taskId);
                const latestExecution = await db.query.executions.findFirst({
                  where: eq(executions.id, executionId),
                });

                const prContent = buildPrContent({
                  task,
                  repo: task.repo,
                  execution: latestExecution!,
                  testRun,
                  filesChanged,
                  commitMessages: [commitMessage],
                });

                const pr = await createPullRequest(githubToken, {
                  owner: task.repo.fullName.split("/")[0],
                  repo: task.repo.fullName.split("/")[1],
                  title: prContent.title,
                  body: prContent.body,
                  head: finalBranch,
                  base: task.repo.prTargetBranch || task.repo.defaultBranch,
                  draft: prContent.draft,
                });

                // Update task to done
                await db
                  .update(tasks)
                  .set({
                    status: "done" as TaskStatus,
                    prUrl: pr.html_url,
                    prNumber: pr.number,
                    statusHistory: buildStatusHistoryAppend({
                      fromStatus: "review",
                      toStatus: "done",
                      triggeredBy: "worker",
                    }),
                    updatedAt: new Date(),
                  })
                  .where(eq(tasks.id, taskId));

                // Clean up pending changes
                await deletePendingChangesByTask(taskId);

                workerLogger.info(
                  { taskId, prUrl: pr.html_url },
                  "Auto-approved: committed, pushed, and created PR",
                );
              }
            }
          } catch (autoApproveError) {
            workerLogger.warn(
              { error: autoApproveError },
              "Auto-approve failed - task remains in review for manual approval",
            );
            // Task stays in review status, user can approve manually
          }
        }
      } catch (collectError) {
        workerLogger.error(
          { error: collectError },
          "Failed to collect file changes",
        );

        // Fall back to stuck status if we can't collect changes
        result.status = "stuck";
        result.error = `Failed to collect changes: ${collectError instanceof Error ? collectError.message : "Unknown error"}`;
      }
    }

    // Handle failed/stuck executions (no changes to this path)
    if (result.status !== "complete") {
      // Update execution status
      await db
        .update(executions)
        .set({
          status: "failed",
          iteration: result.iterations,
          completedAt: new Date(),
          commits: result.commits,
          errorMessage: result.error || null,
        })
        .where(eq(executions.id, executionId));

      // Update task status to stuck
      const taskStatus: TaskStatus = "stuck";
      await db
        .update(tasks)
        .set({
          status: taskStatus,
          statusHistory: buildStatusHistoryAppend({
            fromStatus: "executing",
            toStatus: taskStatus,
            triggeredBy: "worker",
          }),
          processingPhase: null,
          processingJobId: null,
          processingStartedAt: null,
          processingStatusText: null,
          updatedAt: new Date(),
        })
        .where(eq(tasks.id, taskId));

      // Emit stuck event to worker_events
      await db.insert(workerEvents).values({
        workerJobId: workerJob.id,
        eventType: "error",
        content: "Execution stuck",
        metadata: {
          commits: result.commits?.length || 0,
          filesWritten,
          commandsRun,
          error: result.error,
        } as WorkerEventMetadata,
      });

      // Update worker job as failed
      await db
        .update(workerJobs)
        .set({
          status: "failed",
          completedAt: new Date(),
          resultSummary: `Failed after ${result.iterations} iteration${result.iterations !== 1 ? "s" : ""}`,
          errorMessage: result.error || null,
        })
        .where(eq(workerJobs.id, workerJob.id));

      // Publish stuck event to Redis for SSE
      const stuckEvent = createWorkerUpdateEvent(
        taskId,
        task.title,
        task.repo.name,
        "stuck",
        {
          currentAction: "Execution stuck",
          error: result.error,
          completedAt: new Date(),
        },
      );
      await publishWorkerEvent(userId, stuckEvent);

      // Notify dependent tasks about the failure
      await handleCascadingFailure(taskId, task.title, userId, task.repoId);
    }

    // Record usage for billing (only if tokens were tracked)
    if (totalInputTokens > 0 || totalOutputTokens > 0) {
      try {
        await recordUsage({
          userId,
          taskId,
          executionId,
          model: preferredModel,
          inputTokens: totalInputTokens,
          outputTokens: totalOutputTokens,
        });
        workerLogger.info(
          {
            userId,
            taskId,
            inputTokens: totalInputTokens,
            outputTokens: totalOutputTokens,
          },
          "Recorded usage for execution",
        );
      } catch (usageError) {
        // Don't fail the execution if usage recording fails
        workerLogger.error({ error: usageError }, "Failed to record usage");
      }
    }

    if (result.status === "complete") {
      await bus.publish(
        createDomainEvent("ExecutionCompleted", {
          executionId,
          taskId,
          repoId: task.repoId,
          userId,
        }),
      );
    }

    return {
      success: result.status === "complete",
      commits: result.commits,
      error: result.error,
      completedAt: new Date(),
    };
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";

    await bus.publish(
      createDomainEvent("ExecutionFailed", {
        executionId,
        taskId,
        repoId: task.repoId,
        userId,
        reason: errorMessage,
      }),
    );

    // Update execution status
    await db
      .update(executions)
      .set({
        status: "failed",
        completedAt: new Date(),
        errorMessage,
      })
      .where(eq(executions.id, executionId));

    // Update task status with history
    await db
      .update(tasks)
      .set({
        status: "stuck",
        statusHistory: buildStatusHistoryAppend({
          fromStatus: "executing",
          toStatus: "stuck",
          triggeredBy: "worker",
        }),
        updatedAt: new Date(),
      })
      .where(eq(tasks.id, taskId));

    // Update worker job as failed
    await db
      .update(workerJobs)
      .set({
        status: "failed",
        completedAt: new Date(),
        errorMessage,
      })
      .where(eq(workerJobs.id, workerJob.id));

    // Emit error event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "error",
      content: errorMessage,
    });

    // Publish error event to Redis for SSE
    const errorEvent = createWorkerUpdateEvent(
      taskId,
      task.title,
      task.repo.name,
      "stuck",
      {
        currentAction: "Execution failed",
        error: errorMessage,
        completedAt: new Date(),
      },
    );
    await publishWorkerEvent(userId, errorEvent);

    // Notify dependent tasks about the failure
    await handleCascadingFailure(taskId, task.title, userId, task.repoId);

    return {
      success: false,
      error: errorMessage,
      completedAt: new Date(),
    };
  }
}

// Process brainstorm job
async function processBrainstorm(
  job: Job<BrainstormJobData, BrainstormJobResult>,
): Promise<BrainstormJobResult> {
  const { taskId, userId, repoId, continueToPlanning } = job.data;

  workerLogger.info({ taskId }, "Starting brainstorm");

  // Create worker job record
  const [workerJob] = await db
    .insert(workerJobs)
    .values({
      taskId,
      phase: "brainstorming",
      status: "running",
      startedAt: new Date(),
      jobId: job.id,
    })
    .returning();

  try {
    // Get task details
    const task = await db.query.tasks.findFirst({
      where: eq(tasks.id, taskId),
      with: { repo: true },
    });

    if (!task) {
      throw new Error("Task not found");
    }

    const startedAt = task.processingStartedAt || new Date();

    // Decrypt API key on demand from user record (never stored in Redis job data)
    const brainstormUser = await db.query.users.findFirst({
      where: eq(users.id, userId),
    });
    if (!brainstormUser) {
      throw new Error("User not found");
    }
    const brainstormAiConfig = getAIClientConfig(brainstormUser);
    if (!brainstormAiConfig) {
      throw new Error("No AI provider configured for user");
    }

    // Create AI client
    const client = await createAIClient(
      brainstormAiConfig.provider,
      brainstormAiConfig.apiKey,
      brainstormAiConfig.model,
    );

    // Emit thinking event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "thinking",
      content: "Scanning repository context...",
      metadata: { model: brainstormAiConfig.model } as WorkerEventMetadata,
    });

    // Update status: Scanning repository...
    await db
      .update(tasks)
      .set({ processingStatusText: "Scanning repository..." })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        job.id!,
        startedAt,
        {
          statusText: "Scanning repository...",
          progress: 5,
        },
      ),
    );

    // Scan repository for context
    let repoContext: RepoContext = {
      techStack: [],
      fileStructure: [],
      configFiles: [],
    };
    try {
      const githubToken = await getUserGithubToken(userId);
      if (githubToken && task.repo.fullName) {
        const [owner, repoName] = task.repo.fullName.split("/");
        const githubContext = await scanRepoViaGitHub(
          githubToken,
          owner,
          repoName,
          task.repo.defaultBranch || "main",
        );
        repoContext = {
          techStack: githubContext.techStack,
          fileStructure: githubContext.fileStructure,
          configFiles: githubContext.configFiles,
        };
        workerLogger.info(
          { techStack: repoContext.techStack },
          "Repo scan complete for brainstorm",
        );
      }
    } catch (error) {
      workerLogger.error(
        { error },
        "GitHub scan failed during brainstorm, using empty context",
      );
    }

    // Update status: Analyzing task...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.brainstorming[0] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.brainstorming[0],
          progress: 15,
        },
      ),
    );

    // Emit action event
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "action",
      content: "Generating ideas and requirements...",
      metadata: { model: brainstormAiConfig.model } as WorkerEventMetadata,
    });

    // Update status: Generating ideas...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.brainstorming[1] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.brainstorming[1],
          progress: 30,
        },
      ),
    );

    // Run brainstorm with repo context
    const result = (await generateInitialBrainstorm(
      client,
      task.title,
      task.description,
      repoContext,
    )) ?? {
      summary: `Initial analysis of: ${task.title}`,
      requirements: ["Define detailed requirements through refinement"],
      considerations: ["Technical approach needs discussion"],
      suggestedApproach:
        "Use the Refine button to interactively clarify this task",
    };

    // Update status: Finalizing brainstorm...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.brainstorming[3] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.brainstorming[3],
          progress: 80,
        },
      ),
    );

    const brainstormResultJson = JSON.stringify(result, null, 2);

    // Count requirements for result summary
    const requirementsCount = result.requirements?.length || 0;

    // Emit completion event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "complete",
      content: "Brainstorming complete",
      metadata: { requirementsCount } as WorkerEventMetadata,
    });

    // Update worker job as completed
    await db
      .update(workerJobs)
      .set({
        status: "completed",
        completedAt: new Date(),
        resultSummary: `Generated ${requirementsCount} requirement${requirementsCount !== 1 ? "s" : ""}`,
      })
      .where(eq(workerJobs.id, workerJob.id));

    // Update task with result and clear processing state
    await db
      .update(tasks)
      .set({
        brainstormResult: brainstormResultJson,
        processingPhase: null,
        processingJobId: null,
        processingStartedAt: null,
        processingStatusText: null,
        updatedAt: new Date(),
      })
      .where(eq(tasks.id, taskId));

    // Publish completion event
    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_complete",
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        job.id!,
        startedAt,
        {
          statusText: "Brainstorm complete",
          progress: 100,
        },
      ),
    );

    // Also publish a worker update for the Workers page
    await publishWorkerEvent(
      userId,
      createWorkerUpdateEvent(
        taskId,
        task.title,
        task.repo.name,
        "brainstorming",
        {
          currentAction: "Brainstorm complete",
        },
      ),
    );

    workerLogger.info({ taskId }, "Brainstorm complete");

    // If autonomous mode, queue planning job
    if (continueToPlanning) {
      workerLogger.info({ taskId }, "Autonomous mode: queueing plan");

      const bus = initDomainEventSystem();
      const planJob = await publishForJob(
        bus,
        createDomainEvent("TaskPlanningRequested", {
          taskId,
          userId,
          repoId,
          brainstormResult: brainstormResultJson,
          continueToExecution: true,
          repoName: task.repo.name,
          repoFullName: task.repo.fullName,
          repoDefaultBranch: task.repo.defaultBranch || "main",
        }),
      );

      if (!planJob || !planJob.id) {
        throw new Error("Failed to queue plan job");
      }

      // Update task to planning phase with history
      await db
        .update(tasks)
        .set({
          status: "planning",
          statusHistory: buildStatusHistoryAppend({
            fromStatus: "brainstorming",
            toStatus: "planning",
            triggeredBy: "autonomous",
          }),
          processingPhase: "planning",
          processingJobId: planJob.id,
          processingStartedAt: new Date(),
          processingStatusText: phaseStatusMessages.planning[0],
          updatedAt: new Date(),
        })
        .where(eq(tasks.id, taskId));

      // Publish processing_start for planning
      await publishProcessingEvent(
        userId,
        createProcessingEvent(
          "processing_start",
          taskId,
          task.title,
          task.repo.name,
          "planning",
          planJob.id!,
          new Date(),
          {
            statusText: phaseStatusMessages.planning[0],
            progress: 0,
          },
        ),
      );
    }

    return {
      success: true,
      brainstormResult: brainstormResultJson,
      completedAt: new Date(),
    };
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    workerLogger.error(
      { taskId, error: errorMessage },
      "Brainstorm worker error",
    );

    // Update worker job as failed
    await db
      .update(workerJobs)
      .set({
        status: "failed",
        completedAt: new Date(),
        errorMessage,
      })
      .where(eq(workerJobs.id, workerJob.id));

    // Emit error event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "error",
      content: errorMessage,
    });

    // Get task for event publishing
    const failedTask = await db.query.tasks.findFirst({
      where: eq(tasks.id, taskId),
      with: { repo: true },
    });

    const startedAt = failedTask?.processingStartedAt || new Date();

    // Clear processing state and revert status with history
    await db
      .update(tasks)
      .set({
        status: "todo",
        statusHistory: buildStatusHistoryAppend({
          fromStatus: "brainstorming",
          toStatus: "todo",
          triggeredBy: "worker",
        }),
        processingPhase: null,
        processingJobId: null,
        processingStartedAt: null,
        processingStatusText: null,
        updatedAt: new Date(),
      })
      .where(eq(tasks.id, taskId));

    // Publish error event
    if (failedTask) {
      await publishProcessingEvent(
        userId,
        createProcessingEvent(
          "processing_error",
          taskId,
          failedTask.title,
          failedTask.repo.name,
          "brainstorming",
          job.id!,
          startedAt,
          {
            error: errorMessage,
          },
        ),
      );
    }

    return {
      success: false,
      error: errorMessage,
      completedAt: new Date(),
    };
  }
}

// Process plan job
async function processPlan(
  job: Job<PlanJobData, PlanJobResult>,
): Promise<PlanJobResult> {
  const {
    taskId,
    userId,
    repoId,
    brainstormResult,
    continueToExecution,
    repoName,
    repoFullName,
    repoDefaultBranch,
    techStack,
  } = job.data;

  workerLogger.info({ taskId }, "Starting plan");

  // Create worker job record
  const [workerJob] = await db
    .insert(workerJobs)
    .values({
      taskId,
      phase: "planning",
      status: "running",
      startedAt: new Date(),
      jobId: job.id,
    })
    .returning();

  try {
    // Get task details
    const task = await db.query.tasks.findFirst({
      where: eq(tasks.id, taskId),
      with: { repo: true },
    });

    if (!task) {
      throw new Error("Task not found");
    }

    const startedAt = task.processingStartedAt || new Date();

    // Decrypt API key on demand from user record (never stored in Redis job data)
    const planUser = await db.query.users.findFirst({
      where: eq(users.id, userId),
    });
    if (!planUser) {
      throw new Error("User not found");
    }
    const planAiConfig = getAIClientConfig(planUser);
    if (!planAiConfig) {
      throw new Error("No AI provider configured for user");
    }

    // Create AI client
    const client = await createAIClient(
      planAiConfig.provider,
      planAiConfig.apiKey,
      planAiConfig.model,
    );

    // Emit thinking event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "thinking",
      content: "Reviewing brainstorm results...",
      metadata: { model: planAiConfig.model } as WorkerEventMetadata,
    });

    // Update status: Reviewing brainstorm...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.planning[0] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "planning",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.planning[0],
          progress: 10,
        },
      ),
    );

    // Emit action event
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "action",
      content: "Designing implementation plan...",
      metadata: { model: planAiConfig.model } as WorkerEventMetadata,
    });

    // Update status: Designing plan...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.planning[1] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "planning",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.planning[1],
          progress: 30,
        },
      ),
    );

    // Generate plan with repo context
    const result = await generatePlan(
      client,
      task.title,
      task.description,
      brainstormResult,
      {
        name: repoName || task.repo.name,
        fullName: repoFullName || task.repo.fullName,
        defaultBranch: repoDefaultBranch || task.repo.defaultBranch || "main",
        techStack,
      },
    );

    // Update status: Finalizing plan...
    await db
      .update(tasks)
      .set({ processingStatusText: phaseStatusMessages.planning[3] })
      .where(eq(tasks.id, taskId));

    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_update",
        taskId,
        task.title,
        task.repo.name,
        "planning",
        job.id!,
        startedAt,
        {
          statusText: phaseStatusMessages.planning[3],
          progress: 80,
        },
      ),
    );

    const planContentJson = JSON.stringify(result, null, 2);
    const branchName = `loopforge/${taskId.slice(0, 8)}`;

    // Count steps for result summary
    const stepsCount = result.steps?.length || 0;

    // Emit completion event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "complete",
      content: "Planning complete",
      metadata: { stepsCount } as WorkerEventMetadata,
    });

    // Update worker job as completed
    await db
      .update(workerJobs)
      .set({
        status: "completed",
        completedAt: new Date(),
        resultSummary: `Created ${stepsCount}-step plan`,
      })
      .where(eq(workerJobs.id, workerJob.id));

    // Update task with result and clear processing state with history
    const newStatus: TaskStatus = continueToExecution ? "ready" : "planning";
    await db
      .update(tasks)
      .set({
        planContent: planContentJson,
        branch: branchName,
        status: newStatus,
        statusHistory: buildStatusHistoryAppend({
          fromStatus: "planning",
          toStatus: newStatus,
          triggeredBy: continueToExecution ? "autonomous" : "worker",
        }),
        processingPhase: null,
        processingJobId: null,
        processingStartedAt: null,
        processingStatusText: null,
        updatedAt: new Date(),
      })
      .where(eq(tasks.id, taskId));

    // Publish completion event
    await publishProcessingEvent(
      userId,
      createProcessingEvent(
        "processing_complete",
        taskId,
        task.title,
        task.repo.name,
        "planning",
        job.id!,
        startedAt,
        {
          statusText: "Plan complete",
          progress: 100,
        },
      ),
    );

    // Also publish a worker update for the Workers page
    await publishWorkerEvent(
      userId,
      createWorkerUpdateEvent(
        taskId,
        task.title,
        task.repo.name,
        continueToExecution ? "ready" : "planning",
        {
          currentAction: "Plan complete",
        },
      ),
    );

    workerLogger.info({ taskId }, "Plan complete");

    const bus = initDomainEventSystem();
    await bus.publish(
      createDomainEvent("TaskPlanned", {
        taskId,
        userId,
        repoId,
        planSteps: stepsCount,
        autoApprove: continueToExecution,
      }),
    );

    // If autonomous mode, queue execution job
    if (continueToExecution) {
      workerLogger.info({ taskId }, "Autonomous mode: queueing execution");

      // Get repo details
      const repo = await db.query.repos.findFirst({
        where: eq(repos.id, repoId),
      });

      if (!repo) {
        throw new Error("Repository not found");
      }

      // Create execution record
      const [execution] = await db
        .insert(executions)
        .values({
          taskId,
          status: "queued",
          iteration: 0,
        })
        .returning();

      // Update task to executing with history
      await db
        .update(tasks)
        .set({
          status: "executing",
          statusHistory: buildStatusHistoryAppend({
            fromStatus: "ready",
            toStatus: "executing",
            triggeredBy: "autonomous",
          }),
          processingPhase: "executing",
          processingJobId: execution.id,
          processingStartedAt: new Date(),
          processingStatusText: phaseStatusMessages.executing[0],
          updatedAt: new Date(),
        })
        .where(eq(tasks.id, taskId));

      const queuedExecution = await publishForJob(
        bus,
        createDomainEvent("TaskExecutionRequested", {
          executionId: execution.id,
          taskId,
          repoId,
          userId,
          aiProvider: planAiConfig.provider,
          preferredModel: planAiConfig.model,
          planContent: planContentJson,
          branch: branchName,
          defaultBranch: repoDefaultBranch || task.repo.defaultBranch || "main",
          cloneUrl: repo.cloneUrl,
        }),
      );

      if (!queuedExecution || !queuedExecution.id) {
        throw new Error("Failed to queue execution job");
      }

      // Publish executing event
      await publishWorkerEvent(
        userId,
        createWorkerUpdateEvent(
          taskId,
          task.title,
          task.repo.name,
          "executing",
          {
            currentAction: "Starting execution...",
            currentStep: "Step 1",
          },
        ),
      );
    }

    return {
      success: true,
      planContent: planContentJson,
      branch: branchName,
      completedAt: new Date(),
    };
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    workerLogger.error({ taskId, error: errorMessage }, "Plan worker error");

    // Update worker job as failed
    await db
      .update(workerJobs)
      .set({
        status: "failed",
        completedAt: new Date(),
        errorMessage,
      })
      .where(eq(workerJobs.id, workerJob.id));

    // Emit error event to worker_events
    await db.insert(workerEvents).values({
      workerJobId: workerJob.id,
      eventType: "error",
      content: errorMessage,
    });

    // Get task for event publishing
    const failedTask = await db.query.tasks.findFirst({
      where: eq(tasks.id, taskId),
      with: { repo: true },
    });

    const startedAt = failedTask?.processingStartedAt || new Date();

    // Clear processing state and revert status with history
    await db
      .update(tasks)
      .set({
        status: "brainstorming",
        statusHistory: buildStatusHistoryAppend({
          fromStatus: "planning",
          toStatus: "brainstorming",
          triggeredBy: "worker",
        }),
        processingPhase: null,
        processingJobId: null,
        processingStartedAt: null,
        processingStatusText: null,
        updatedAt: new Date(),
      })
      .where(eq(tasks.id, taskId));

    // Publish error event
    if (failedTask) {
      await publishProcessingEvent(
        userId,
        createProcessingEvent(
          "processing_error",
          taskId,
          failedTask.title,
          failedTask.repo.name,
          "planning",
          job.id!,
          startedAt,
          {
            error: errorMessage,
          },
        ),
      );
    }

    return {
      success: false,
      error: errorMessage,
      completedAt: new Date(),
    };
  }
}

// Create and start the execution worker
const worker = createExecutionWorker(processExecution);

worker.on("completed", (job, result) => {
  workerLogger.info(
    { jobId: job.id, success: result.success },
    "Job completed",
  );
});

worker.on("failed", async (job, err) => {
  workerLogger.error({ jobId: job?.id, error: err.message }, "Job failed");

  // If we have job data, ensure all records are updated to failed state
  // This catches cases where the error occurred before the try-catch block
  if (job?.data) {
    const { executionId, taskId, userId } = job.data;

    try {
      // Get task info for error event
      const task = await db.query.tasks.findFirst({
        where: eq(tasks.id, taskId),
        with: { repo: true },
      });

      await handleExecutionFailure(err, {
        executionId,
        taskId,
        userId,
        repoName: task?.repo?.name,
        taskTitle: task?.title,
      });
    } catch (failureErr) {
      workerLogger.error(
        { error: failureErr, originalError: err.message },
        "Failed to handle execution failure cleanup",
      );
    }
  }
});

worker.on("error", (err) => {
  workerLogger.error({ error: err }, "Worker error");
});

workerLogger.info("Execution worker started");

// Create and start the autonomous flow worker
const autonomousWorker = createAutonomousFlowWorker();

autonomousWorker.on("completed", (job, result) => {
  workerLogger.info(
    { jobId: job.id, success: result.success, finalStatus: result.finalStatus },
    "Autonomous flow completed",
  );
});

autonomousWorker.on("failed", (job, err) => {
  workerLogger.error(
    { jobId: job?.id, error: err.message },
    "Autonomous flow failed",
  );
});

autonomousWorker.on("error", (err) => {
  workerLogger.error({ error: err }, "Autonomous flow worker error");
});

workerLogger.info("Autonomous flow worker started");

// Create and start the brainstorm worker
const brainstormWorker = createBrainstormWorker(processBrainstorm);

brainstormWorker.on("completed", (job, result) => {
  workerLogger.info(
    { jobId: job.id, success: result.success },
    "Brainstorm job completed",
  );
});

brainstormWorker.on("failed", (job, err) => {
  workerLogger.error(
    { jobId: job?.id, error: err.message },
    "Brainstorm job failed",
  );
});

brainstormWorker.on("error", (err) => {
  workerLogger.error({ error: err }, "Brainstorm worker error");
});

workerLogger.info("Brainstorm worker started");

// Create and start the plan worker
const planWorker = createPlanWorker(processPlan);

planWorker.on("completed", (job, result) => {
  workerLogger.info(
    { jobId: job.id, success: result.success },
    "Plan job completed",
  );
});

planWorker.on("failed", (job, err) => {
  workerLogger.error({ jobId: job?.id, error: err.message }, "Plan job failed");
});

planWorker.on("error", (err) => {
  workerLogger.error({ error: err }, "Plan worker error");
});

workerLogger.info("Plan worker started");

// Graceful shutdown handler
async function gracefulShutdown(signal: string) {
  workerLogger.info({ signal }, "Received shutdown signal, closing workers...");
  await Promise.allSettled([
    worker.close(),
    autonomousWorker.close(),
    brainstormWorker.close(),
    planWorker.close(),
  ]);
  process.exit(0);
}

process.on("SIGTERM", () => gracefulShutdown("SIGTERM"));
process.on("SIGINT", () => gracefulShutdown("SIGINT"));

export { worker, autonomousWorker, brainstormWorker, planWorker };
export default worker;
